### PR TITLE
First draft of update service

### PR DESCRIPTION
**Pull request by Chippelius**

### CODE REVIEW

**Comment by Chippelius** [comment]
In theory it works already. The problem is that the bluetooth adapter can handle only one search request at a time, so when pressing the search button on the devices page, it takes until the completion of the current update-service-interval (currently 10 seconds) until the search even starts. If someone sets the update-service interval to a minute, it could take that long until available devices start showing up on the devices page. 

I see these options to resolve that: 
Either we use cancellation tokens to cancel the update service search as soon as someone presses the Search button and let it resume afterwards. That would mean that while searching for available devices, the GPS coordinates of the known devices are not being updated (for 20 seconds, as that is how long the search is currently configured to take). 
Or we remove the search button, save the available devices in the bluetooth service instead of the items viewmodel and keep that list up-to-date via the constantly running update service. The problem with that is that if the update service interval is set to a minute, the available devices will only update once a minute. 
I would suggest a combination of these two ideas: Change the bluetooth service so that you can register (multiple) event listeners instead of one static search method and give it an async trigger-search method that stops the current (potentially long-running) search and starts a new one immediately. 

@NicoStellwag what's your opinion?

**Comment by NicoStellwag** [comment]
> In theory it works already. The problem is that the bluetooth adapter can handle only one search request at a time, so when pressing the search button on the devices page, it takes until the completion of the current update-service-interval (currently 10 seconds) until the search even starts. If someone sets the update-service interval to a minute, it could take that long until available devices start showing up on the devices page.
> 
> I see these options to resolve that: Either we use cancellation tokens to cancel the update service search as soon as someone presses the Search button and let it resume afterwards. That would mean that while searching for available devices, the GPS coordinates of the known devices are not being updated (for 20 seconds, as that is how long the search is currently configured to take). Or we remove the search button, save the available devices in the bluetooth service instead of the items viewmodel and keep that list up-to-date via the constantly running update service. The problem with that is that if the update service interval is set to a minute, the available devices will only update once a minute. I would suggest a combination of these two ideas: Change the bluetooth service so that you can register (multiple) event listeners instead of one static search method and give it an async trigger-search method that stops the current (potentially long-running) search and starts a new one immediately.
> 
> @NicoStellwag what's your opinion?

I have a couple of points:
First of all, we should't have the service constantly scanning for devices, as that drains the battery really fast (see section "General BLE iOS, Android" of this [readme](https://github.com/xabre/xamarin-bluetooth-le)). This may be acceptable for a foreground service as we implement it now, but becomes completely impracticable as soon as we move to a background service implementation. (Even if we don't do this as part of amos anymore, I suspect the industry partner will have to in the long run.) Instead I would simply periodically try to connect to all devices in the database and use that as an indicator. That would also eliminate the problem you mentioned above. (I see that this approach introduces some other problems, especially with fast moving users, but imo this is the lesser evil compared to a background service potentially draining the battery in 1-2 hours.)

I will implement the suggested changes after lunch, then we can decide on one of the approaches together.

**Comment by Chippelius** [comment]
Well, the problem is that, as far as I understand it, a search means simply sending one (or pontentially a few) broadcast messages and listening for answers. Trying to connect to a specific device involves constantly sending connection requests until a certain timeout has been reached. So trying to connect to all saved devices once is potentially draining way more power than searching for all devices in the vicinity. (Although I'm not sure if my assumptions on this are correct.) 
And I can also imagine that trying to connect occupies the adapter in the same way a search does, so (background) searching for 10 seconds and trying to connect for 10 seconds might equally keep the user who pressed the search button waiting.

**Comment by NicoStellwag** [comment]
> Well, the problem is that, as far as I understand it, a search means simply sending one (or pontentially a few) broadcast messages and listening for answers. Trying to connect to a specific device involves constantly sending connection requests until a certain timeout has been reached. So trying to connect to all saved devices once is potentially draining way more power than searching for all devices in the vicinity. (Although I'm not sure if my assumptions on this are correct.) And I can also imagine that trying to connect occupies the adapter in the same way a search does, so (background) searching for 10 seconds and trying to connect for 10 seconds might equally keep the user who pressed the search button waiting.

While scanning the smartphone has to make sure it also finds devices that get in reach during the scanning period, so it would constantly have to broadcast. I assume connecting is pretty much the same as transmitting data and timeout's use is giving the beacon some time to respond to the connection request. [This](https://stackoverflow.com/questions/38359570/ble-transmitting-vs-receiving-energy-consumption) kind of confirms that. The connection timeout could be a problem, though. Let me test how long it is real quick.

**Comment by Chippelius** [comment]
> Edit: I just tested it. It is possible to connect to multiple devices at the same time, so the timeout should not be a problem. I will implement it either tonight or tomorrow morning, I don't know if I will find the time today yet.

Okay, but is it also possible to scan for available devices while trying to connect to the known devices?

**Comment by NicoStellwag** [comment]
> > Edit: I just tested it. It is possible to connect to multiple devices at the same time, so the timeout should not be a problem. I will implement it either tonight or tomorrow morning, I don't know if I will find the time today yet.
> 
> Okay, but is it also possible to scan for available devices while trying to connect to the known devices?

It seems like the adapter sequentializes all calls and prioritises scanning higher than connecting.
See this excerpt from a test run's output:
```
[UpdateService] 26.06.2022 16:41:44 Out of reach: test 
00000000-0000-0000-0000-2eb292f0bf68
00000000-0000-0000-0000-2eb292f0bf68
[UpdateService] 26.06.2022 16:42:00 Reachable: test 
```
(The polling interval is set to 5s and the Guids should represent discovered devices)

**Comment by NicoStellwag** [comment]
@Chippelius 
I just commited my implementation using connection attempts instead of scanning.
It introduces some delay in recognizing any changes, but I personally think the tradeoff is worth it.
Would be happy about feedback if you find time to test it.

**Comment by Chippelius** [comment]
I tested it and was almost happy, only had to make some minor changes, I hope you're okay with them. 
If so, please approve it, then I can merge.

**Comment by NicoStellwag** [comment]
> I tested it and was almost happy, only had to make some minor changes, I hope you're okay with them. If so, please approve it, then I can merge.

The changes make sense to me.
I'm currently in a meeting and want to build and test the branch one more time before I approve, so I'll need about an hour.

**Review by NicoStellwag — APPROVED** [review]
did a final test real quick, settings work as expected

**Pull request merged**
