### PR TITLE
compute circle-sizes dependent on used display

### PR DESCRIPTION
**Pull request by domi1504**
Signed-off-by: Dominik Pysch <domi.pysch@gmail.com>

### CODE REVIEW

**Review by NicoStellwag — APPROVED** [review]
Can't confirm that it fixes the problem since I never had it in the first place.
But the app looks fine and the code makes sense to me.

**Comment by Wandinad** [comment]
The circle is now the right size for me, but there is still some content which is not completely visible:
grafik

**Review by Interperle — APPROVED** [review]
Works for me too

**Comment by domi1504** [comment]
@Wandinad, the screen is scrollable, right? Is the rest of the box visible if you scroll downwards?

**Comment by Wandinad** [comment]
> @Wandinad, the screen is scrollable, right? Is the rest of the box visible if you scroll downwards?

Yes, the view is scrollable. But I think the name of the device should be instantly visible without scrolling. Maybe it is somewhat of an edge case, since the display size might not be that common anymore.

**Comment by domi1504** [comment]
Ok, I reworked the UI of the page again. 
Now, it should work. But I suspect I know why this issue comes up on some devices (same issue on my emulator): Xamarin does not compute the height of the android navigation-bar on some devices. It sets this frame "at the bottom of the page". 
But "at the bottom" turns out to be beneath the nav-bar. I could not find out yet on which devices this occurs.

**Pull request merged**
